language: rust
sudo: false
matrix:
  include:
    - rust: 1.32.0
      script:
        - |
            cargo build --verbose --no-default-features &&
            cargo build --verbose --features "$FEATURES" &&
            cargo test --verbose --features "$FEATURES"
    - rust: stable
      script:
        - |
            cargo build --verbose --no-default-features &&
            cargo build --verbose --features "$FEATURES" &&
            cargo test --verbose --features "$FEATURES" &&
            cargo bench --verbose --features "$FEATURES"
    - rust: beta
      script:
        - |
            cargo build --verbose --no-default-features &&
            cargo build --verbose --features "$FEATURES" &&
            cargo test --verbose --features "$FEATURES" &&
            cargo bench --verbose --features "$FEATURES"
    - rust: nightly
      script:
        - |
            cargo build --verbose --no-default-features &&
            cargo build --verbose --features "$FEATURES" &&
            cargo test --verbose --features "$FEATURES" &&
            cargo bench --verbose --features "$FEATURES"
branches:
  only:
    - master
    # bors branches
    - staging
    - trying
